Revert "CMake: Set standard to C++17"
This reverts commit 878e3e905bc8ab0b6fdb96ef7c62954af655c750.
error C2872: 'byte': ambiguous symbol from M$ rpcndr.h